### ISSUE TITLE
Coinの[表]と[裏]のファイル名

### ISSUE THREAD

**Issue by daicyan** [Mafty-Hs/Udonite#3]
0.8.0.8のZipファイルを展開すると、
udonite/assets/images/dice/2_coin/2_coin[#U8868].png
udonite/assets/images/dice/2_coin/2_coin[#U88cf].png
が404になりました。
HTTPリクエストを見ると
assets/images/dice/2_coin/2_coin[%E8%A1%A8].png
assets/images/dice/2_coin/2_coin[%E8%A3%8F].png
になっているので、ZIPファイルではUTF8の「表」「裏」になっていないことが原因だと思われます。
日本語ファイル名にしないほうが良いと思います。

**Comment by Mafty-Hs** [comment]
報告ありがとうございます。
確かにファイル名変えたほう良さそうなので早めに修正書けます

**Comment by Mafty-Hs** [comment]
クライアント0.8.9、サーバー1.0.4にて修正をかけ、日本語ファイル名を変更しました
