### ISSUE TITLE
不具合疑義：「他のキャラクターに乗る」のチェックを外していても他のキャラクターに乗ってしまう

### ISSUE THREAD

**Issue by B-biker** [Mafty-Hs/Udonite#4]
失礼いたします。
自宅環境にてUdoniteを動かしていたところ、表記の事象を確認致しました。
以下に詳細を記載しますので、再現の確認をしていただけると幸いです。

## 不具合疑義内容
ルーム内において、「他のキャラクターに乗る」のチェックが**外れている**キャラクターをドラッグし、他のキャラクターの頭部付近でドロップすると、高度0のままルームの床より高い位置に配置される。水平面上の位置は「他のキャラクター」と同一となる

## 再現方法
1. ロビーページにアクセスする
2. 空き部屋の「新規作成」ボタンを押下する
3. 「ルームデータのロード」にて、後述のルームデータを読み込む
4. 「新しいルームを作成」ボタンを押下する
5. 新規プレイヤーで「ルームに入室」ボタンを押下する
6. キャラクター「ローグ１」をドラッグし、キャラクター「ファイター2」の画像の中央付近にてドロップする

※実際に操作を行った動画を添付致しますので、併せてご確認頂けると幸いです

## 結果
「ローグ１」がテーブル盤面上の「ファイター２」と同じマスの高い位置に配置される
UdonariumWithFlyにて「他のキャラクターに乗る」を**有効**にしている場合と同様の動作

## 期待する結果
「ローグ1」がテーブル盤面上の「ファイター2」の画像の裏にあるマスに配置される
UdonariumWithFlyにて「他のキャラクターに乗る」を**無効**にしている場合と同様の動作

## 使用したサンプルルームデータ
ダンジョンズ＆ドラゴンズ日本公式サイト(https://hobbyjapan.co.jp/dd/)の
サポートページ内にて無料配布されている
ユドナリウム向けデータの「腐敗の影」ルームデータ

通常ユドナリウム用のデータのため
キャラクターは初期状態で全て「他のキャラクターに乗る」が無効となっている

## 実行環境
クライアント機：
Windows 11 Home 21H2
Google Chrome バージョン: 99.0.4844.82（Official Build） （64 ビット）

サーバー機(クライアント側アプリケーションのビルド含む)：
Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-35-generic x86_64)
nginx version: nginx/1.18.0 (Ubuntu)
Angular CLI: 13.2.6
Node: 16.14.2
Package Manager: npm 8.5.0
MongoDB server version: 3.6.8

https://user-images.githubusercontent.com/102040995/159320758-1bf8af9f-c3ca-46b8-ba8f-5aa33e88c4a6.mp4

**Comment by Mafty-Hs** [comment]
報告ありがとうございます
こちらでも確認しました。
原因も特定できたので、次の更新で修正します。

**Comment by Mafty-Hs** [comment]
1.0.2で修正を実施しました。
