### ISSUE TITLE
configの不具合: templateに存在するtrailing slashを残すとエラーとなる

### ISSUE THREAD

**Issue by h-mikisato** [Mafty-Hs/Udonite#5]
src/assets/config.yaml.template における `server.url` の項は `https://test.example/` となっておりますが、
ここの `test.example` の項のみを自ドメインに書き換えて、例えば `https://my.udonite.example.org/` とした上で実行した場合に、
クライアントのJavascriptが `//_allData` という二重スラッシュにアクセスしようとして404となってしまい不具合が発生する事象を確認しました。
`https://my.udonite.example.org` とtrailing slashを削除する修正をすることで正しく動作します。

こちら、templateの方を修正するべきか、コードの方をtrailing slashがあっても正しく動作するべきか判断がつかなかったため、issueとさせていただきました。

**Comment by Mafty-Hs** [comment]
報告ありがとうございます
コード側で対応するのが筋だと思うので、次回更新時にどちらでも動作するように修正を行います

**Comment by Mafty-Hs** [comment]
1.0.2で修正を実施しました。
