### ISSUE TITLE
不具合疑義：画像を外部から取得しているキャラクターzipデータを読み込むと画像が表示されない

### ISSUE THREAD

**Issue by B-biker** [Mafty-Hs/Udonite#7]
失礼いたします。
自宅環境にてUdoniteを動かしていたところ、表記の事象を確認致しました。
以下に詳細を記載致します。
下名環境での設定不備が原因の可能性もありますので
確認していただけると幸いです。
また、Udoniteにおいては外部URLからの画像取得を意図的に禁止する仕様であった場合は申し訳ございません。

### 不具合疑義内容
ルーム内において、画像を外部から取得しているキャラクターzipデータを読み込むと画像が表示されない

### 再現方法
1. ロビーページにアクセスする
2. 空き部屋の「新規作成」ボタンを押下する
3. 「新しいルームを作成」ボタンを押下する
4. 新規プレイヤーで「ルームに入室」ボタンを押下する
5. 「ファイル」→「ZIP読み込み」にて後述のキャラクターデータを読み込む

### 結果
画像の無いキャラクターデータが読み込まれる

### 期待する結果
画像を伴うキャラクターデータが読み込まれる
本家Udonariumと同様の動作

### 使用したサンプルデータ
以下のページにてダウンロード可能な
ダンジョンズ＆ドラゴンズ5版用モンスターキャラクターを使用しております。
https://direboar.github.io/githubpage-test/dist/#/Udonarium

ダウンロードしたzipファイル内に、各モンスターのzipファイルが格納されております。
各モンスターのzipファイル自体には画像データが含まれておらず
xmlファイル内にて画像のURLが記載されております。

### 実行環境
クライアント機：
Windows 11 Home 21H2(OSビルド22000.556、Windows 機能エクスペリエンス パック 1000.22000.556.0)
Google Chrome : 100.0.4896.75（Official Build） （64 ビット）

サーバー機：
Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-39-generic x86_64)
nginx version: nginx/1.18.0 (Ubuntu)
Angular CLI: 13.2.6
Node: 16.14.2
Package Manager: npm 8.5.0
MongoDB server version: 3.6.8
Udonite 1.0.3
udonite-server 1.0.7

**Comment by Mafty-Hs** [comment]
報告ありがとうございます。事象こちらでも確認しました。
原因も特定できたため、次回リリースで修正見込みです。

**Comment by Mafty-Hs** [comment]
1.1.0で修正を実施しました。
近日リリース見込みです
